version: '3.9'
services:
  db:
    image: postgres:13.5-alpine
    network_mode: "host"
    ports:
     - "5432:5432"
    environment:
     - POSTGRES_PASSWORD=$DB_PASS
     - POSTGRES_USER=$DB_USER
     - DB_NAME=$DB_NAME
    volumes:
      - postgres_vol:/var/lib/postgresql/data
      - $PWD/db_init_scripts/create_user_and_db.sh:/docker-entrypoint-initdb.d/create_user_and_db.sh:ro

volumes:
  postgres_vol: