# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'simple.ui'
#
# Created: Sat Dec 14 11:29:17 2013
#      by: PyQt4 UI code generator 4.10.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(850, 550)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setProperty("QmodelIndex", _fromUtf8(""))
        self.centralwidget = QtGui.QWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setFocusPolicy(QtCore.Qt.TabFocus)
        self.centralwidget.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.sourceList = QtGui.QListView(self.centralwidget)
        self.sourceList.setGeometry(QtCore.QRect(20, 60, 351, 481))
        self.sourceList.setAcceptDrops(True)
        self.sourceList.setDragEnabled(True)
        self.sourceList.setDragDropOverwriteMode(True)
        self.sourceList.setDragDropMode(QtGui.QAbstractItemView.DragDrop)
        self.sourceList.setDefaultDropAction(QtCore.Qt.CopyAction)
        self.sourceList.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.sourceList.setObjectName(_fromUtf8("sourceList"))
        self.pathLine = QtGui.QLineEdit(self.centralwidget)
        self.pathLine.setGeometry(QtCore.QRect(60, 30, 721, 25))
        self.pathLine.setMaxLength(32765)
        self.pathLine.setDragEnabled(True)
        self.pathLine.setObjectName(_fromUtf8("pathLine"))
        self.pathLabel = QtGui.QLabel(self.centralwidget)
        self.pathLabel.setGeometry(QtCore.QRect(20, 30, 41, 31))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pathLabel.sizePolicy().hasHeightForWidth())
        self.pathLabel.setSizePolicy(sizePolicy)
        self.pathLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.pathLabel.setObjectName(_fromUtf8("pathLabel"))
        self.exitButton = QtGui.QPushButton(self.centralwidget)
        self.exitButton.setGeometry(QtCore.QRect(690, 510, 146, 25))
        self.exitButton.setObjectName(_fromUtf8("exitButton"))
        self.upButton = QtGui.QPushButton(self.centralwidget)
        self.upButton.setGeometry(QtCore.QRect(800, 30, 31, 25))
        self.upButton.setObjectName(_fromUtf8("upButton"))
        self.textBrowser = QtGui.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(380, 270, 461, 231))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser.sizePolicy().hasHeightForWidth())
        self.textBrowser.setSizePolicy(sizePolicy)
        self.textBrowser.setObjectName(_fromUtf8("textBrowser"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(380, 60, 461, 211))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.fEPSPanalyser = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fEPSPanalyser.sizePolicy().hasHeightForWidth())
        self.fEPSPanalyser.setSizePolicy(sizePolicy)
        self.fEPSPanalyser.setObjectName(_fromUtf8("fEPSPanalyser"))
        self.verticalLayoutWidget_2 = QtGui.QWidget(self.fEPSPanalyser)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 20, 441, 163))
        self.verticalLayoutWidget_2.setObjectName(_fromUtf8("verticalLayoutWidget_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.frequency_line = QtGui.QLineEdit(self.verticalLayoutWidget_2)
        self.frequency_line.setObjectName(_fromUtf8("frequency_line"))
        self.gridLayout_2.addWidget(self.frequency_line, 0, 2, 1, 1)
        self.substance_line = QtGui.QLineEdit(self.verticalLayoutWidget_2)
        self.substance_line.setObjectName(_fromUtf8("substance_line"))
        self.gridLayout_2.addWidget(self.substance_line, 1, 2, 1, 1)
        self.label_3 = QtGui.QLabel(self.verticalLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_2.addWidget(self.label_3, 1, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.verticalLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_2.addWidget(self.label_2, 0, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.database_checkBox = QtGui.QCheckBox(self.verticalLayoutWidget_2)
        self.database_checkBox.setChecked(True)
        self.database_checkBox.setObjectName(_fromUtf8("database_checkBox"))
        self.verticalLayout.addWidget(self.database_checkBox)
        self.debugBox = QtGui.QCheckBox(self.verticalLayoutWidget_2)
        self.debugBox.setObjectName(_fromUtf8("debugBox"))
        self.verticalLayout.addWidget(self.debugBox)
        self.manualFibreSearchBox = QtGui.QCheckBox(self.verticalLayoutWidget_2)
        self.manualFibreSearchBox.setChecked(False)
        self.manualFibreSearchBox.setObjectName(_fromUtf8("manualFibreSearchBox"))
        self.verticalLayout.addWidget(self.manualFibreSearchBox)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.smoothBox = QtGui.QSpinBox(self.verticalLayoutWidget_2)
        self.smoothBox.setProperty("value", 7)
        self.smoothBox.setObjectName(_fromUtf8("smoothBox"))
        self.horizontalLayout_5.addWidget(self.smoothBox)
        self.label_6 = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_5.addWidget(self.label_6)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout.addLayout(self.verticalLayout)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.fEPSP_button = QtGui.QPushButton(self.verticalLayoutWidget_2)
        self.fEPSP_button.setObjectName(_fromUtf8("fEPSP_button"))
        self.horizontalLayout.addWidget(self.fEPSP_button)
        spacerItem1 = QtGui.QSpacerItem(10, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.tabWidget.addTab(self.fEPSPanalyser, _fromUtf8(""))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.verticalLayoutWidget = QtGui.QWidget(self.tab)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 431, 128))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_4.setMargin(0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label_12 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.verticalLayout_4.addWidget(self.label_12)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.expToDelete = QtGui.QComboBox(self.verticalLayoutWidget)
        self.expToDelete.setObjectName(_fromUtf8("expToDelete"))
        self.horizontalLayout_6.addWidget(self.expToDelete)
        self.expToDeleteRefresh = QtGui.QPushButton(self.verticalLayoutWidget)
        self.expToDeleteRefresh.setObjectName(_fromUtf8("expToDeleteRefresh"))
        self.horizontalLayout_6.addWidget(self.expToDeleteRefresh)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.delComplete = QtGui.QRadioButton(self.verticalLayoutWidget)
        self.delComplete.setChecked(True)
        self.delComplete.setObjectName(_fromUtf8("delComplete"))
        self.verticalLayout_4.addWidget(self.delComplete)
        self.delResults = QtGui.QRadioButton(self.verticalLayoutWidget)
        self.delResults.setObjectName(_fromUtf8("delResults"))
        self.verticalLayout_4.addWidget(self.delResults)
        self.Delete = QtGui.QPushButton(self.verticalLayoutWidget)
        self.Delete.setObjectName(_fromUtf8("Delete"))
        self.verticalLayout_4.addWidget(self.Delete)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.exportTab = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.exportTab.sizePolicy().hasHeightForWidth())
        self.exportTab.setSizePolicy(sizePolicy)
        self.exportTab.setObjectName(_fromUtf8("exportTab"))
        self.verticalLayoutWidget_3 = QtGui.QWidget(self.exportTab)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(10, 20, 441, 158))
        self.verticalLayoutWidget_3.setObjectName(_fromUtf8("verticalLayoutWidget_3"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setSizeConstraint(QtGui.QLayout.SetNoConstraint)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label = QtGui.QLabel(self.verticalLayoutWidget_3)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_3.addWidget(self.label)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.exportExpName = QtGui.QComboBox(self.verticalLayoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.exportExpName.sizePolicy().hasHeightForWidth())
        self.exportExpName.setSizePolicy(sizePolicy)
        self.exportExpName.setObjectName(_fromUtf8("exportExpName"))
        self.horizontalLayout_2.addWidget(self.exportExpName)
        self.exportRefresh = QtGui.QPushButton(self.verticalLayoutWidget_3)
        self.exportRefresh.setObjectName(_fromUtf8("exportRefresh"))
        self.horizontalLayout_2.addWidget(self.exportRefresh)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem2)
        self.label_4 = QtGui.QLabel(self.verticalLayoutWidget_3)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout_3.addWidget(self.label_4)
        self.exportSpike = QtGui.QSpinBox(self.verticalLayoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.exportSpike.sizePolicy().hasHeightForWidth())
        self.exportSpike.setSizePolicy(sizePolicy)
        self.exportSpike.setMaximum(190)
        self.exportSpike.setProperty("value", 1)
        self.exportSpike.setObjectName(_fromUtf8("exportSpike"))
        self.verticalLayout_3.addWidget(self.exportSpike)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem3)
        self.label_5 = QtGui.QLabel(self.verticalLayoutWidget_3)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout_3.addWidget(self.label_5)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.exportFilename = QtGui.QLineEdit(self.verticalLayoutWidget_3)
        self.exportFilename.setObjectName(_fromUtf8("exportFilename"))
        self.horizontalLayout_4.addWidget(self.exportFilename)
        self.exportButton = QtGui.QPushButton(self.verticalLayoutWidget_3)
        self.exportButton.setObjectName(_fromUtf8("exportButton"))
        self.horizontalLayout_4.addWidget(self.exportButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.tabWidget.addTab(self.exportTab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab_2.sizePolicy().hasHeightForWidth())
        self.tab_2.setSizePolicy(sizePolicy)
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.frame = QtGui.QFrame(self.tab_2)
        self.frame.setGeometry(QtCore.QRect(20, 10, 321, 171))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtGui.QFrame.Panel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.horizontalLayoutWidget_3 = QtGui.QWidget(self.frame)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(10, 130, 301, 41))
        self.horizontalLayoutWidget_3.setObjectName(_fromUtf8("horizontalLayoutWidget_3"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.saveDbButton = QtGui.QPushButton(self.horizontalLayoutWidget_3)
        self.saveDbButton.setObjectName(_fromUtf8("saveDbButton"))
        self.horizontalLayout_3.addWidget(self.saveDbButton)
        self.clearDbButton = QtGui.QPushButton(self.horizontalLayoutWidget_3)
        self.clearDbButton.setObjectName(_fromUtf8("clearDbButton"))
        self.horizontalLayout_3.addWidget(self.clearDbButton)
        self.layoutWidget = QtGui.QWidget(self.tab_2)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 20, 301, 120))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.gridLayout_4 = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayout_4.setSizeConstraint(QtGui.QLayout.SetNoConstraint)
        self.gridLayout_4.setMargin(0)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label_7 = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_4.addWidget(self.label_7, 2, 0, 1, 1)
        self.dbNameLine = QtGui.QLineEdit(self.layoutWidget)
        self.dbNameLine.setObjectName(_fromUtf8("dbNameLine"))
        self.gridLayout_4.addWidget(self.dbNameLine, 2, 1, 1, 1)
        self.label_8 = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_4.addWidget(self.label_8, 3, 0, 1, 1)
        self.dbUserLine = QtGui.QLineEdit(self.layoutWidget)
        self.dbUserLine.setObjectName(_fromUtf8("dbUserLine"))
        self.gridLayout_4.addWidget(self.dbUserLine, 3, 1, 1, 1)
        self.label_9 = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_4.addWidget(self.label_9, 4, 0, 1, 1)
        self.dbPassLine = QtGui.QLineEdit(self.layoutWidget)
        self.dbPassLine.setObjectName(_fromUtf8("dbPassLine"))
        self.gridLayout_4.addWidget(self.dbPassLine, 4, 1, 1, 1)
        self.label_10 = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_4.addWidget(self.label_10, 0, 0, 1, 2)
        self.dbServerIpLine = QtGui.QLineEdit(self.layoutWidget)
        self.dbServerIpLine.setObjectName(_fromUtf8("dbServerIpLine"))
        self.gridLayout_4.addWidget(self.dbServerIpLine, 1, 1, 1, 1)
        self.label_11 = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_4.addWidget(self.label_11, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        MainWindow.setCentralWidget(self.centralwidget)
        self.pathLabel.setBuddy(self.pathLine)
        self.label_3.setBuddy(self.substance_line)
        self.label_2.setBuddy(self.frequency_line)
        self.label_7.setBuddy(self.dbNameLine)
        self.label_8.setBuddy(self.dbUserLine)
        self.label_9.setBuddy(self.dbPassLine)
        self.label_11.setBuddy(self.dbServerIpLine)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.exitButton, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "fEPSP_analyser", None))
        self.pathLine.setText(_translate("MainWindow", "../tests/ethalon/", None))
        self.pathLabel.setText(_translate("MainWindow", "Path:", None))
        self.exitButton.setText(_translate("MainWindow", "Exit", None))
        self.upButton.setText(_translate("MainWindow", "../", None))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Краткое руководство</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">1. </span>В адресной строке (сверху) указать полный или частичный путь к папке с файлами .dat. Можно пользоваться для перехода панелью слева.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">2. </span>В поле &quot;Tags&quot; указать ключевые слова, которые в дальнейшем облегчат поиск в базе данных.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">3. </span>Нажать кнопку &quot;Start&quot;. Начнется поиск спайков в файлах и определение их характеристик. Вся собранная информация сохраняется в базе данных.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">4. </span>Перейти на вкладку &quot;Export&quot;.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">5.</span> Выбрать название проанализированного эксперимента (папки с файлами .dat). При необходимости изменить номер интересующего спайка и название экспортного файла.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">6. </span>Нажать &quot;Export&quot;. На диске будет создан текстовый файл с амплитудами спайков выбранного эксперимента. </p></body></html>", None))
        self.frequency_line.setText(_translate("MainWindow", "200000", None))
        self.label_3.setText(_translate("MainWindow", "Tags", None))
        self.label_2.setText(_translate("MainWindow", "Frequency", None))
        self.database_checkBox.setText(_translate("MainWindow", "Write to database", None))
        self.debugBox.setText(_translate("MainWindow", "Debug", None))
        self.manualFibreSearchBox.setText(_translate("MainWindow", "Manual fibre search", None))
        self.label_6.setText(_translate("MainWindow", "Smooth coefficient", None))
        self.fEPSP_button.setText(_translate("MainWindow", "Start", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.fEPSPanalyser), _translate("MainWindow", "fEPSP-analyser", None))
        self.label_12.setText(_translate("MainWindow", "Experiment name:", None))
        self.expToDeleteRefresh.setText(_translate("MainWindow", "Refresh", None))
        self.delComplete.setText(_translate("MainWindow", "Delete saved source data and results", None))
        self.delResults.setText(_translate("MainWindow", "Delete results only", None))
        self.Delete.setText(_translate("MainWindow", "Delete", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Delete", None))
        self.label.setText(_translate("MainWindow", "Experiment name", None))
        self.exportRefresh.setText(_translate("MainWindow", "Refresh", None))
        self.label_4.setText(_translate("MainWindow", "Spike number", None))
        self.label_5.setText(_translate("MainWindow", "Filename", None))
        self.exportButton.setText(_translate("MainWindow", "Export", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.exportTab), _translate("MainWindow", "Export", None))
        self.saveDbButton.setText(_translate("MainWindow", "Save db config", None))
        self.clearDbButton.setText(_translate("MainWindow", "Clear db config", None))
        self.label_7.setText(_translate("MainWindow", "Database Name", None))
        self.label_8.setText(_translate("MainWindow", "User Name", None))
        self.label_9.setText(_translate("MainWindow", "Password", None))
        self.label_10.setText(_translate("MainWindow", "DataBase configuration", None))
        self.label_11.setText(_translate("MainWindow", "Server address", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "config", None))

