# Form implementation generated from reading ui file 'simple.ui'
#
# Created: Sat Dec 14 11:29:17 2013
#      by: PyQt4 UI code generator 4.10.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtWidgets

try:
    _encoding = QtWidgets.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtCore.QCoreApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtCore.QCoreApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(850, 550)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setProperty("QmodelIndex", "")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setFocusPolicy(QtCore.Qt.TabFocus)
        self.centralwidget.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.centralwidget.setObjectName("centralwidget")
        self.sourceList = QtWidgets.QListView(self.centralwidget)
        self.sourceList.setGeometry(QtCore.QRect(20, 60, 351, 481))
        self.sourceList.setAcceptDrops(True)
        self.sourceList.setDragEnabled(True)
        self.sourceList.setDragDropOverwriteMode(True)
        self.sourceList.setDragDropMode(QtWidgets.QAbstractItemView.DragDrop)
        self.sourceList.setDefaultDropAction(QtCore.Qt.CopyAction)
        self.sourceList.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.sourceList.setObjectName("sourceList")
        self.pathLine = QtWidgets.QLineEdit(self.centralwidget)
        self.pathLine.setGeometry(QtCore.QRect(60, 30, 721, 25))
        self.pathLine.setMaxLength(32765)
        self.pathLine.setDragEnabled(True)
        self.pathLine.setObjectName("pathLine")
        self.pathLabel = QtWidgets.QLabel(self.centralwidget)
        self.pathLabel.setGeometry(QtCore.QRect(20, 30, 41, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pathLabel.sizePolicy().hasHeightForWidth())
        self.pathLabel.setSizePolicy(sizePolicy)
        self.pathLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.pathLabel.setObjectName("pathLabel")
        self.exitButton = QtWidgets.QPushButton(self.centralwidget)
        self.exitButton.setGeometry(QtCore.QRect(690, 510, 146, 25))
        self.exitButton.setObjectName("exitButton")
        self.upButton = QtWidgets.QPushButton(self.centralwidget)
        self.upButton.setGeometry(QtCore.QRect(800, 30, 31, 25))
        self.upButton.setObjectName("upButton")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(380, 270, 461, 231))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser.sizePolicy().hasHeightForWidth())
        self.textBrowser.setSizePolicy(sizePolicy)
        self.textBrowser.setObjectName("textBrowser")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(380, 60, 461, 211))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName("tabWidget")
        self.fEPSPanalyser = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fEPSPanalyser.sizePolicy().hasHeightForWidth())
        self.fEPSPanalyser.setSizePolicy(sizePolicy)
        self.fEPSPanalyser.setObjectName("fEPSPanalyser")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.fEPSPanalyser)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 20, 441, 163))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frequency_line = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.frequency_line.setObjectName("frequency_line")
        self.gridLayout_2.addWidget(self.frequency_line, 0, 2, 1, 1)
        self.substance_line = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.substance_line.setObjectName("substance_line")
        self.gridLayout_2.addWidget(self.substance_line, 1, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.database_checkBox = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.database_checkBox.setChecked(True)
        self.database_checkBox.setObjectName("database_checkBox")
        self.verticalLayout.addWidget(self.database_checkBox)
        self.debugBox = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.debugBox.setObjectName("debugBox")
        self.verticalLayout.addWidget(self.debugBox)
        self.manualFibreSearchBox = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.manualFibreSearchBox.setChecked(False)
        self.manualFibreSearchBox.setObjectName("manualFibreSearchBox")
        self.verticalLayout.addWidget(self.manualFibreSearchBox)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.smoothBox = QtWidgets.QSpinBox(self.verticalLayoutWidget_2)
        self.smoothBox.setProperty("value", 7)
        self.smoothBox.setObjectName("smoothBox")
        self.horizontalLayout_5.addWidget(self.smoothBox)
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_5.addWidget(self.label_6)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout.addLayout(self.verticalLayout)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.fEPSP_button = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.fEPSP_button.setObjectName("fEPSP_button")
        self.horizontalLayout.addWidget(self.fEPSP_button)
        spacerItem1 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.tabWidget.addTab(self.fEPSPanalyser, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.tab)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 431, 128))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_12 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_4.addWidget(self.label_12)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.expToDelete = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.expToDelete.setObjectName("expToDelete")
        self.horizontalLayout_6.addWidget(self.expToDelete)
        self.expToDeleteRefresh = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.expToDeleteRefresh.setObjectName("expToDeleteRefresh")
        self.horizontalLayout_6.addWidget(self.expToDeleteRefresh)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.delComplete = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.delComplete.setChecked(True)
        self.delComplete.setObjectName("delComplete")
        self.verticalLayout_4.addWidget(self.delComplete)
        self.delResults = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.delResults.setObjectName("delResults")
        self.verticalLayout_4.addWidget(self.delResults)
        self.Delete = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.Delete.setObjectName("Delete")
        self.verticalLayout_4.addWidget(self.Delete)
        self.tabWidget.addTab(self.tab, "")
        self.exportTab = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.exportTab.sizePolicy().hasHeightForWidth())
        self.exportTab.setSizePolicy(sizePolicy)
        self.exportTab.setObjectName("exportTab")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.exportTab)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(10, 20, 441, 158))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.exportExpName = QtWidgets.QComboBox(self.verticalLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.exportExpName.sizePolicy().hasHeightForWidth())
        self.exportExpName.setSizePolicy(sizePolicy)
        self.exportExpName.setObjectName("exportExpName")
        self.horizontalLayout_2.addWidget(self.exportExpName)
        self.exportRefresh = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.exportRefresh.setObjectName("exportRefresh")
        self.horizontalLayout_2.addWidget(self.exportRefresh)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem2)
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.exportSpike = QtWidgets.QSpinBox(self.verticalLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.exportSpike.sizePolicy().hasHeightForWidth())
        self.exportSpike.setSizePolicy(sizePolicy)
        self.exportSpike.setMaximum(190)
        self.exportSpike.setProperty("value", 1)
        self.exportSpike.setObjectName("exportSpike")
        self.verticalLayout_3.addWidget(self.exportSpike)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem3)
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_3.addWidget(self.label_5)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.exportFilename = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.exportFilename.setObjectName("exportFilename")
        self.horizontalLayout_4.addWidget(self.exportFilename)
        self.exportButton = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.exportButton.setObjectName("exportButton")
        self.horizontalLayout_4.addWidget(self.exportButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.tabWidget.addTab(self.exportTab, "")
        self.tab_2 = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab_2.sizePolicy().hasHeightForWidth())
        self.tab_2.setSizePolicy(sizePolicy)
        self.tab_2.setObjectName("tab_2")
        self.frame = QtWidgets.QFrame(self.tab_2)
        self.frame.setGeometry(QtCore.QRect(20, 10, 321, 171))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.frame)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(10, 130, 301, 41))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.saveDbButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.saveDbButton.setObjectName("saveDbButton")
        self.horizontalLayout_3.addWidget(self.saveDbButton)
        self.clearDbButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.clearDbButton.setObjectName("clearDbButton")
        self.horizontalLayout_3.addWidget(self.clearDbButton)
        self.layoutWidget = QtWidgets.QWidget(self.tab_2)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 20, 301, 120))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_4.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_7 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setObjectName("label_7")
        self.gridLayout_4.addWidget(self.label_7, 2, 0, 1, 1)
        self.dbNameLine = QtWidgets.QLineEdit(self.layoutWidget)
        self.dbNameLine.setObjectName("dbNameLine")
        self.gridLayout_4.addWidget(self.dbNameLine, 2, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setObjectName("label_8")
        self.gridLayout_4.addWidget(self.label_8, 3, 0, 1, 1)
        self.dbUserLine = QtWidgets.QLineEdit(self.layoutWidget)
        self.dbUserLine.setObjectName("dbUserLine")
        self.gridLayout_4.addWidget(self.dbUserLine, 3, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setObjectName("label_9")
        self.gridLayout_4.addWidget(self.label_9, 4, 0, 1, 1)
        self.dbPassLine = QtWidgets.QLineEdit(self.layoutWidget)
        self.dbPassLine.setObjectName("dbPassLine")
        self.gridLayout_4.addWidget(self.dbPassLine, 4, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setObjectName("label_10")
        self.gridLayout_4.addWidget(self.label_10, 0, 0, 1, 2)
        self.dbServerIpLine = QtWidgets.QLineEdit(self.layoutWidget)
        self.dbServerIpLine.setObjectName("dbServerIpLine")
        self.gridLayout_4.addWidget(self.dbServerIpLine, 1, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setObjectName("label_11")
        self.gridLayout_4.addWidget(self.label_11, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.pathLabel.setBuddy(self.pathLine)
        self.label_3.setBuddy(self.substance_line)
        self.label_2.setBuddy(self.frequency_line)
        self.label_7.setBuddy(self.dbNameLine)
        self.label_8.setBuddy(self.dbUserLine)
        self.label_9.setBuddy(self.dbPassLine)
        self.label_11.setBuddy(self.dbServerIpLine)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.exitButton.clicked.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "fEPSP_analyser", None))
        self.pathLine.setText(_translate("MainWindow", "../tests/ethalon/", None))
        self.pathLabel.setText(_translate("MainWindow", "Path:", None))
        self.exitButton.setText(_translate("MainWindow", "Exit", None))
        self.upButton.setText(_translate("MainWindow", "../", None))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Краткое руководство</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">1. </span>В адресной строке (сверху) указать полный или частичный путь к папке с файлами .dat. Можно пользоваться для перехода панелью слева.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">2. </span>В поле &quot;Tags&quot; указать ключевые слова, которые в дальнейшем облегчат поиск в базе данных.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">3. </span>Нажать кнопку &quot;Start&quot;. Начнется поиск спайков в файлах и определение их характеристик. Вся собранная информация сохраняется в базе данных.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">4. </span>Перейти на вкладку &quot;Export&quot;.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">5.</span> Выбрать название проанализированного эксперимента (папки с файлами .dat). При необходимости изменить номер интересующего спайка и название экспортного файла.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">6. </span>Нажать &quot;Export&quot;. На диске будет создан текстовый файл с амплитудами спайков выбранного эксперимента. </p></body></html>", None))
        self.frequency_line.setText(_translate("MainWindow", "200000", None))
        self.label_3.setText(_translate("MainWindow", "Tags", None))
        self.label_2.setText(_translate("MainWindow", "Frequency", None))
        self.database_checkBox.setText(_translate("MainWindow", "Write to database", None))
        self.debugBox.setText(_translate("MainWindow", "Debug", None))
        self.manualFibreSearchBox.setText(_translate("MainWindow", "Manual fibre search", None))
        self.label_6.setText(_translate("MainWindow", "Smooth coefficient", None))
        self.fEPSP_button.setText(_translate("MainWindow", "Start", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.fEPSPanalyser), _translate("MainWindow", "fEPSP-analyser", None))
        self.label_12.setText(_translate("MainWindow", "Experiment name:", None))
        self.expToDeleteRefresh.setText(_translate("MainWindow", "Refresh", None))
        self.delComplete.setText(_translate("MainWindow", "Delete saved source data and results", None))
        self.delResults.setText(_translate("MainWindow", "Delete results only", None))
        self.Delete.setText(_translate("MainWindow", "Delete", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Delete", None))
        self.label.setText(_translate("MainWindow", "Experiment name", None))
        self.exportRefresh.setText(_translate("MainWindow", "Refresh", None))
        self.label_4.setText(_translate("MainWindow", "Spike number", None))
        self.label_5.setText(_translate("MainWindow", "Filename", None))
        self.exportButton.setText(_translate("MainWindow", "Export", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.exportTab), _translate("MainWindow", "Export", None))
        self.saveDbButton.setText(_translate("MainWindow", "Save db config", None))
        self.clearDbButton.setText(_translate("MainWindow", "Clear db config", None))
        self.label_7.setText(_translate("MainWindow", "Database Name", None))
        self.label_8.setText(_translate("MainWindow", "User Name", None))
        self.label_9.setText(_translate("MainWindow", "Password", None))
        self.label_10.setText(_translate("MainWindow", "DataBase configuration", None))
        self.label_11.setText(_translate("MainWindow", "Server address", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "config", None))

